### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by tabascoz** [ecmnet/MAVComm#3]
Hello, 

I'm planning to test MAVGCL in order to analyze live  data sent from 3dr radio telemetry, however I couldn't find any information on how to use the Mavcomm. 

I have successfully compiled the code but it doesn't seem to bound to my 3dr radio serial port. 
I'm running gentoo linux. Which parameteres are expected from mavcomm.jar to be called? 

Thanks in advance

pro2 dis # java -jar mavcomm.jar 

Initializing (msp.properties)...
Configuration file'msp.properties' not found.
MSPControlService version Build tmp
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/ptr/ByReference
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.comino.mav.comm.highspeedserial.SerialAMA0.<init>(Unknown Source)
    at com.comino.mav.comm.highspeedserial.MAVHighSpeedSerialComm.<init>(Unknown Source)
    at com.comino.mav.comm.highspeedserial.MAVHighSpeedSerialComm.getInstance(Unknown Source)
    at com.comino.mav.control.impl.MAVProxyController.<init>(Unknown Source)
    at com.comino.msp.main.StartUp.<init>(Unknown Source)
    at com.comino.msp.main.StartUp.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.ptr.ByReference
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 18 more

**Comment by ecmnet** [comment]
I am not quite sure, what you want to setup. I run MAVComm on a RPI-2 connecting to PIXHAWK by serial connection and providing data to MAVGCL via UDP. I assume you are using the 3DR Radio to establish a connection between your vehicle and your computer, right? Currently, this is not implemented in MAVGCL as this would require to connect MAVGCL directly with a serial connection. On the other hand, MAVGCL uses MAVComm internally, so minor changes in `com.comino.flight.MainApp` could do the job. Here `MAVUdpController(peerAddress,14555,14550, false);` needs to be replaced by `MAVSerialController` using an appropriate serial setup.

Although this setup seems to be possible with some tweaks, I doubt, that this makes sense, as the data transmission rate to MAVGCL is far to low then.

**Comment by tabascoz** [comment]
Thanks for the explanation!  My idea was to analyze the data over 3ds serial, however  I see the point about the serial speed. Will try to run a RPI-2 board ( my gentoo minidlna server ), just need some space to assemble everything on my drone.

**Comment by ecmnet** [comment]
You could either use [MAVProxy](http://wiki.ros.org/mavros) or MAVComm on your RPI-2. I strongly recommend to setup the RPi-2 as an access point for WLAN.
